<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHsMJQc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHsMJQc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHsMJQc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHsMJQc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHsMJQc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHsMJQc',
    'container.build_id' => '6027309c',
    'container.build_time' => 1697838054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHsMJQc');
